-- Widens core.assets.asset_type and core.instruments.instrument_type to
-- accept 'FX' (BE-003a / RM0 DEC-006). FX represents a non-tradable exchange
-- rate reference (currently only fx:coingecko:usdt-usd), not a
-- PortfolioMember candidate -- see doc/technical/03_universe_data.md §7 and
-- doc/ai_quant_trading_system_requirements.md §5.1.2.
--
-- This file follows 001_roles_and_core.sql and 002_core_catalog_seed.sql: it
-- only runs automatically via docker-entrypoint-initdb.d on a FRESH
-- PostgreSQL data volume. Existing dev/staging databases must have this
-- applied manually by a role with core-schema write access (core.assets and
-- core.instruments are owned by xr_core_owner; xr_market_data_owner only has
-- REFERENCES/SELECT on them, see 001_roles_and_core.sql) -- see
-- deploy/postgres/apply_core_fx_type.sql, which carries the identical ALTER
-- statements below for that manual path.
--
-- The original CHECK constraints were declared inline on the column
-- (`... CHECK (asset_type IN (...))`), so PostgreSQL assigned them an
-- autogenerated name. Rather than guess that name, this looks it up from
-- pg_constraint by column membership before dropping it, then adds a
-- deliberately-named replacement so any future widening does not have to
-- repeat this lookup.

SET ROLE xr_core_owner;

DO $$
DECLARE
    existing_constraint text;
BEGIN
    SELECT conname INTO existing_constraint
    FROM pg_constraint
    WHERE conrelid = 'core.assets'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) ILIKE '%asset_type%';
    IF existing_constraint IS NOT NULL THEN
        EXECUTE format('ALTER TABLE core.assets DROP CONSTRAINT %I', existing_constraint);
    END IF;
END
$$;

ALTER TABLE core.assets
    ADD CONSTRAINT ck_assets_asset_type
    CHECK (asset_type IN ('STOCK', 'ETF', 'CRYPTO', 'CASH', 'FX'));

DO $$
DECLARE
    existing_constraint text;
BEGIN
    SELECT conname INTO existing_constraint
    FROM pg_constraint
    WHERE conrelid = 'core.instruments'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) ILIKE '%instrument_type%';
    IF existing_constraint IS NOT NULL THEN
        EXECUTE format('ALTER TABLE core.instruments DROP CONSTRAINT %I', existing_constraint);
    END IF;
END
$$;

ALTER TABLE core.instruments
    ADD CONSTRAINT ck_instruments_instrument_type
    CHECK (instrument_type IN ('EQUITY', 'ETF', 'SPOT', 'FX'));

RESET ROLE;
